//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPMAA.PlanificacionesSRV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlanificacionesSRV.IPlanificacion")]
    public interface IPlanificacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanificacion/ObtenerPlanificaciones", ReplyAction="http://tempuri.org/IPlanificacion/ObtenerPlanificacionesResponse")]
        Entidades.Planificaciones[] ObtenerPlanificaciones(Entidades.Planificaciones oFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanificacion/ObtenerPlanificaciones", ReplyAction="http://tempuri.org/IPlanificacion/ObtenerPlanificacionesResponse")]
        System.Threading.Tasks.Task<Entidades.Planificaciones[]> ObtenerPlanificacionesAsync(Entidades.Planificaciones oFiltro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlanificacionChannel : SPMAA.PlanificacionesSRV.IPlanificacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlanificacionClient : System.ServiceModel.ClientBase<SPMAA.PlanificacionesSRV.IPlanificacion>, SPMAA.PlanificacionesSRV.IPlanificacion {
        
        public PlanificacionClient() {
        }
        
        public PlanificacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlanificacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanificacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanificacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.Planificaciones[] ObtenerPlanificaciones(Entidades.Planificaciones oFiltro) {
            return base.Channel.ObtenerPlanificaciones(oFiltro);
        }
        
        public System.Threading.Tasks.Task<Entidades.Planificaciones[]> ObtenerPlanificacionesAsync(Entidades.Planificaciones oFiltro) {
            return base.Channel.ObtenerPlanificacionesAsync(oFiltro);
        }
    }
}
