//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiService.Test.PlanificacionesSRV {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Planificaciones", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Planificaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApiService.Test.PlanificacionesSRV.Contratos ContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApiService.Test.PlanificacionesSRV.Trabajos TrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VisitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoContrato {
            get {
                return this.CodigoContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoContratoField, value) != true)) {
                    this.CodigoContratoField = value;
                    this.RaisePropertyChanged("CodigoContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTrabajo {
            get {
                return this.CodigoTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTrabajoField, value) != true)) {
                    this.CodigoTrabajoField = value;
                    this.RaisePropertyChanged("CodigoTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiService.Test.PlanificacionesSRV.Contratos Contrato {
            get {
                return this.ContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContratoField, value) != true)) {
                    this.ContratoField = value;
                    this.RaisePropertyChanged("Contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiService.Test.PlanificacionesSRV.Trabajos Trabajo {
            get {
                return this.TrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.TrabajoField, value) != true)) {
                    this.TrabajoField = value;
                    this.RaisePropertyChanged("Trabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Visita {
            get {
                return this.VisitaField;
            }
            set {
                if ((this.VisitaField.Equals(value) != true)) {
                    this.VisitaField = value;
                    this.RaisePropertyChanged("Visita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contratos", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Contratos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApiService.Test.PlanificacionesSRV.Clientes ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTecnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InicioStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApiService.Test.PlanificacionesSRV.Tecnicos TecnicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiService.Test.PlanificacionesSRV.Clientes Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoClienteField, value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTecnico {
            get {
                return this.CodigoTecnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTecnicoField, value) != true)) {
                    this.CodigoTecnicoField = value;
                    this.RaisePropertyChanged("CodigoTecnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fin {
            get {
                return this.FinField;
            }
            set {
                if ((this.FinField.Equals(value) != true)) {
                    this.FinField = value;
                    this.RaisePropertyChanged("Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinString {
            get {
                return this.FinStringField;
            }
            set {
                if ((object.ReferenceEquals(this.FinStringField, value) != true)) {
                    this.FinStringField = value;
                    this.RaisePropertyChanged("FinString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((this.InicioField.Equals(value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InicioString {
            get {
                return this.InicioStringField;
            }
            set {
                if ((object.ReferenceEquals(this.InicioStringField, value) != true)) {
                    this.InicioStringField = value;
                    this.RaisePropertyChanged("InicioString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiService.Test.PlanificacionesSRV.Tecnicos Tecnico {
            get {
                return this.TecnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.TecnicoField, value) != true)) {
                    this.TecnicoField = value;
                    this.RaisePropertyChanged("Tecnico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trabajos", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Trabajos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tecnicos", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Tecnicos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadContratosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadContratos {
            get {
                return this.CantidadContratosField;
            }
            set {
                if ((this.CantidadContratosField.Equals(value) != true)) {
                    this.CantidadContratosField = value;
                    this.RaisePropertyChanged("CantidadContratos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlanificacionesSRV.IPlanificacion")]
    public interface IPlanificacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanificacion/ObtenerPlanificaciones", ReplyAction="http://tempuri.org/IPlanificacion/ObtenerPlanificacionesResponse")]
        ApiService.Test.PlanificacionesSRV.Planificaciones[] ObtenerPlanificaciones(ApiService.Test.PlanificacionesSRV.Planificaciones oFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanificacion/ObtenerPlanificaciones", ReplyAction="http://tempuri.org/IPlanificacion/ObtenerPlanificacionesResponse")]
        System.Threading.Tasks.Task<ApiService.Test.PlanificacionesSRV.Planificaciones[]> ObtenerPlanificacionesAsync(ApiService.Test.PlanificacionesSRV.Planificaciones oFiltro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlanificacionChannel : ApiService.Test.PlanificacionesSRV.IPlanificacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlanificacionClient : System.ServiceModel.ClientBase<ApiService.Test.PlanificacionesSRV.IPlanificacion>, ApiService.Test.PlanificacionesSRV.IPlanificacion {
        
        public PlanificacionClient() {
        }
        
        public PlanificacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlanificacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanificacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanificacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApiService.Test.PlanificacionesSRV.Planificaciones[] ObtenerPlanificaciones(ApiService.Test.PlanificacionesSRV.Planificaciones oFiltro) {
            return base.Channel.ObtenerPlanificaciones(oFiltro);
        }
        
        public System.Threading.Tasks.Task<ApiService.Test.PlanificacionesSRV.Planificaciones[]> ObtenerPlanificacionesAsync(ApiService.Test.PlanificacionesSRV.Planificaciones oFiltro) {
            return base.Channel.ObtenerPlanificacionesAsync(oFiltro);
        }
    }
}
